name: Build and Push Docker Image

on:
  push:
    branches: [ master ]

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      # Log in to Docker Hub using the secrets
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }} # Use the secret for the username
          password: ${{ secrets.DOCKERHUB_TOKEN }}    # Use the secret for the token

      # Build and push the image (Example step)
      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/your-repo-name:latest
